<a href="https://colab.research.google.com/github/Jumiranda28/Projeto_integrador/blob/main/PII2_bronze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Steps:
#Arquitetura Medelhão
#1 - Bronze - Abrir o CSV via python, dar uma olhada, salvar um arquivo .Parquet, o nome CSL no arquivo significa que vai para etapa Silver
#2 - Silver - Abrir .Parquet via python, tratar duplicados, tratar nulls, colocar os DataTypes corretos, salvar um arquivo .Parquet, o nome TGT no arquivo significa que vai para etapa Gold
#3 - Gold

In [8]:
#To connect with Google Drive
from google.colab import drive
drive.mount('/content/drive')
google_drive_prefix = "/content/drive/MyDrive/cdai/csv/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
import pandas as pd

df = pd.read_csv(f"{google_drive_prefix}history.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

In [ ]:
duplicates = df[df.duplicated()]
print(duplicates)

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn, CustomerFeedback, MonthlyIncome]
Index: []

[0 rows x 23 columns]

In [ ]:
nan_rows = df[df.isnull().T.any()]
nan_rows

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
7,8020-BWHYL,Female,1,No,No,15,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Credit card (automatic),75.30,NaN,Yes,I recently canceled my service with this provi...,353
49,6996-KNSML,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,74.90,NaN,Yes,I recently switched to this internet provider ...,5422
64,4951-UKAAQ,Female,0,No,No,4,Yes,Yes,Fiber optic,No,...,No,Yes,Month-to-month,Yes,Electronic check,88.95,NaN,Yes,I recently decided to cancel my fiber optic in...,1323
79,9360-AHGNL,Female,1,Yes,No,43,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,One year,Yes,Mailed check,109.55,NaN,Yes,I have been a customer with this company for o...,6588
122,7253-UVNDW,Female,0,No,No,46,Yes,No,DSL,No,...,No,No,Two year,No,Credit card (automatic),54.35,NaN,Yes,I have been a customer with this company for 4...,5277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5535,4918-FYJNT,Female,1,Yes,No,55,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,No,Electronic check,90.45,NaN,No,"""I have been a customer with this company for ...",2487
5546,2108-YKQTY,Female,0,No,No,4,Yes,No,DSL,No,...,No,No,Month-to-month,No,Credit card (automatic),50.70,NaN,Yes,I recently switched to this DSL internet servi...,6670
5552,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,No,Two year,No,Mailed check,73.35,NaN,No,I recently signed up for a two-year contract f...,8056
5592,0723-VSOBE,Female,1,No,No,45,No,No phone service,DSL,No,...,No,Yes,One year,No,Electronic check,34.20,NaN,No,I have been a customer with this company for 4...,625
5594,7538-GWHML,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,No,Electronic check,69.65,NaN,Yes,I recently switched to this fiber optic intern...,7408

In [ ]:
df.loc[:, df.isnull().any()].columns

Index(['TotalCharges'], dtype='object')

In [ ]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure               object
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
CustomerFeedback     object
MonthlyIncome         int64
dtype: object

In [10]:
name_of_step = "csl"

terrasignal_parquet_filename = "t_his_terrasignal" + name_of_step + ".parquet"

df.to_parquet(google_drive_prefix + terrasignal_parquet_filename, engine="pyarrow", compression="snappy")